### ISSUE TITLE
Crashing upon in-line comments after load

### ISSUE THREAD

**Issue by joe-p** [dragmz/vscode-teal#3]
I've been experiencing crashes when typing comments after `load` statements. Haven't experienced this anywhere else

![CleanShot 2023-02-24 at 09 39 10](https://user-images.githubusercontent.com/50534337/221206046-8a7f458c-b08c-4f0e-8bb4-5903fa0bab9f.gif)

```
panic: runtime error: index out of range [59] with length 59

goroutine 1 [running]:
github.com/dragmz/teal.Process({0x14000284900, 0x409})
	/home/runner/work/teal/teal/process.go:3303 +0xda0
github.com/dragmz/teal/lsp.(*lspDoc).Results(...)
	/home/runner/work/teal/teal/lsp/lsp.go:50
github.com/dragmz/teal/lsp.(*lsp).prepare(0x10490fe80?, {0x1400013ae40?, 0x98?})
	/home/runner/work/teal/teal/lsp/lsp.go:800 +0x5c
github.com/dragmz/teal/lsp.(*lsp).handle(0x140003038c0, {{0x14000605f38, 0x3}, {0x104894480, 0x14000605f50}, {0x14000138f60, 0x20}, {0x0, 0x0}, {0x0, ...}}, ...)
	/home/runner/work/teal/teal/lsp/lsp.go:1763 +0x3730
github.com/dragmz/teal/lsp.(*lsp).Run.func2(0x140003038c0)
	/home/runner/work/teal/teal/lsp/lsp.go:2293 +0x154
github.com/dragmz/teal/lsp.(*lsp).Run(0x140003038c0)
	/home/runner/work/teal/teal/lsp/lsp.go:2299 +0x7c
main.runLsp({{0x0, 0x0}, {0x0, 0x0}, {0x1047ace0d, 0x3}})
	/home/runner/work/teal/teal/cmd/tealsp/main.go:58 +0x23c
main.main()
	/home/runner/work/teal/teal/cmd/tealsp/main.go:107 +0x358
[Info  - 9:37:10 AM] Connection to server got closed. Server will restart.
panic: runtime error: index out of range [59] with length 59

goroutine 1 [running]:
github.com/dragmz/teal.Process({0x140002dd680, 0x409})
	/home/runner/work/teal/teal/process.go:3303 +0xda0
github.com/dragmz/teal/lsp.(*lspDoc).Results(...)
	/home/runner/work/teal/teal/lsp/lsp.go:50
github.com/dragmz/teal/lsp.(*lsp).handle(0x14000303900, {{0x1400021a700, 0x3}, {0x105358480, 0x1400021a708}, {0x1400021c2d0, 0x17}, {0x0, 0x0}, {0x0, ...}}, ...)
	/home/runner/work/teal/teal/lsp/lsp.go:1705 +0x16f0
github.com/dragmz/teal/lsp.(*lsp).Run.func2(0x14000303900)
	/home/runner/work/teal/teal/lsp/lsp.go:2293 +0x154
github.com/dragmz/teal/lsp.(*lsp).Run(0x14000303900)
	/home/runner/work/teal/teal/lsp/lsp.go:2299 +0x7c
main.runLsp({{0x0, 0x0}, {0x0, 0x0}, {0x105270e0d, 0x3}})
	/home/runner/work/teal/teal/cmd/tealsp/main.go:58 +0x23c
main.main()
	/home/runner/work/teal/teal/cmd/tealsp/main.go:107 +0x358
[Info  - 9:37:10 AM] Connection to server got closed. Server will restart.
panic: runtime error: index out of range [59] with length 59

goroutine 1 [running]:
github.com/dragmz/teal.Process({0x140001fb680, 0x409})
	/home/runner/work/teal/teal/process.go:3303 +0xda0
github.com/dragmz/teal/lsp.(*lspDoc).Results(...)
	/home/runner/work/teal/teal/lsp/lsp.go:50
github.com/dragmz/teal/lsp.(*lsp).handle(0x140002d18c0, {{0x14000354790, 0x3}, {0x104f00480, 0x14000354798}, {0x14000356318, 0x17}, {0x0, 0x0}, {0x0, ...}}, ...)
	/home/runner/work/teal/teal/lsp/lsp.go:1705 +0x16f0
github.com/dragmz/teal/lsp.(*lsp).Run.func2(0x140002d18c0)
	/home/runner/work/teal/teal/lsp/lsp.go:2293 +0x154
github.com/dragmz/teal/lsp.(*lsp).Run(0x140002d18c0)
	/home/runner/work/teal/teal/lsp/lsp.go:2299 +0x7c
main.runLsp({{0x0, 0x0}, {0x0, 0x0}, {0x104e18e0d, 0x3}})
	/home/runner/work/teal/teal/cmd/tealsp/main.go:58 +0x23c
main.main()
	/home/runner/work/teal/teal/cmd/tealsp/main.go:107 +0x358
[Info  - 9:37:10 AM] Connection to server got closed. Server will restart.
panic: runtime error: index out of range [59] with length 59

goroutine 1 [running]:
github.com/dragmz/teal.Process({0x140002df680, 0x409})
	/home/runner/work/teal/teal/process.go:3303 +0xda0
github.com/dragmz/teal/lsp.(*lspDoc).Results(...)
	/home/runner/work/teal/teal/lsp/lsp.go:50
github.com/dragmz/teal/lsp.(*lsp).handle(0x14000305880, {{0x14000222720, 0x3}, {0x1050d0480, 0x14000222728}, {0x140002242e8, 0x17}, {0x0, 0x0}, {0x0, ...}}, ...)
	/home/runner/work/teal/teal/lsp/lsp.go:1705 +0x16f0
github.com/dragmz/teal/lsp.(*lsp).Run.func2(0x14000305880)
	/home/runner/work/teal/teal/lsp/lsp.go:2293 +0x154
github.com/dragmz/teal/lsp.(*lsp).Run(0x14000305880)
	/home/runner/work/teal/teal/lsp/lsp.go:2299 +0x7c
main.runLsp({{0x0, 0x0}, {0x0, 0x0}, {0x104fe8e0d, 0x3}})
	/home/runner/work/teal/teal/cmd/tealsp/main.go:58 +0x23c
main.main()
	/home/runner/work/teal/teal/cmd/tealsp/main.go:107 +0x358
[Info  - 9:37:10 AM] Connection to server got closed. Server will restart.
panic: runtime error: index out of range [59] with length 59

goroutine 1 [running]:
github.com/dragmz/teal.Process({0x140000dbb00, 0x409})
	/home/runner/work/teal/teal/process.go:3303 +0xda0
github.com/dragmz/teal/lsp.(*lspDoc).Results(...)
	/home/runner/work/teal/teal/lsp/lsp.go:50
github.com/dragmz/teal/lsp.(*lsp).handle(0x14000354d40, {{0x140003c8a80, 0x3}, {0x104d74480, 0x140003c8a88}, {0x140003cc3c0, 0x17}, {0x0, 0x0}, {0x0, ...}}, ...)
	/home/runner/work/teal/teal/lsp/lsp.go:1705 +0x16f0
github.com/dragmz/teal/lsp.(*lsp).Run.func2(0x14000354d40)
	/home/runner/work/teal/teal/lsp/lsp.go:2293 +0x154
github.com/dragmz/teal/lsp.(*lsp).Run(0x14000354d40)
	/home/runner/work/teal/teal/lsp/lsp.go:2299 +0x7c
main.runLsp({{0x0, 0x0}, {0x0, 0x0}, {0x104c8ce0d, 0x3}})
	/home/runner/work/teal/teal/cmd/tealsp/main.go:58 +0x23c
main.main()
	/home/runner/work/teal/teal/cmd/tealsp/main.go:107 +0x358
[Error - 9:37:10 AM] The TEAL Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by dragmz** [comment]
@joe-p can you provide the full source code or at least the code near to line 60 in the editor?

**Comment by dragmz** [comment]
I can reproduce with:
```teal
int 1 /
b a
```

**Comment by dragmz** [comment]
https://github.com/dragmz/teal/commit/c7ea919352a4fb837fb1c9044696d4170ba075f1 should fix it

Please update (Ctrl + Shift + P -> TEAL: Install/Update Tools)
